name: extended_button
description: A wrapper of ElevatedButton to support gradient background and transform and image background.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

