name: enhanced_button
description: A wrapper of ElevatedButton to support gradient background and transform and image background.
version: 0.0.2
repository: https://github.com/shirne/extended_button

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

