name: enhanced_button
description: A wrapper of ElevatedButton to support gradient background and transform and image background.
version: 0.1.0
repository: https://github.com/shirne/extended_button
screenshots:
  - description: "button efects"
    path: preview/enhanced_button.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
